# Generated by Django 5.2.14 on 2026-06-02 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogParam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('param_type', models.CharField(choices=[('VEHICLE_MODEL', 'Vehicle Model'), ('COLOR', 'Color'), ('WARRANTY_TYPE', 'Warranty Type'), ('CAMPAIGN_CODE', 'Campaign Code')], max_length=20)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('concesionaria', models.CharField(choices=[('SURMOTOR', 'Surmotor'), ('GRANDA_CENTENO', 'Granda Centeno'), ('SHYRIS', 'Shyris')], max_length=20)),
            ],
            options={
                'db_table': 'catalog_params',
                'ordering': ['param_type', 'name'],
                'unique_together': {('param_type', 'code', 'concesionaria')},
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('catalog_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concesionaria', models.CharField(choices=[('SURMOTOR', 'Surmotor'), ('GRANDA_CENTENO', 'Granda Centeno'), ('SHYRIS', 'Shyris')], max_length=20)),
            ],
            options={
                'db_table': 'spare_parts',
                'ordering': ['name'],
                'unique_together': {('catalog_code', 'concesionaria')},
            },
        ),
        migrations.CreateModel(
            name='Srg',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('ot', models.CharField(db_index=True, max_length=20, unique=True)),
                ('srg_type', models.CharField(choices=[('WARRANTY', 'Garantía'), ('CAMPAIGN', 'Campaña')], max_length=10)),
                ('status', models.CharField(choices=[('PROCESO', 'Proceso'), ('PENDIENTE', 'Pendiente'), ('PREAPROBADO', 'Preaprobado'), ('APROBADO', 'Aprobado'), ('RETORNADO', 'Retornado'), ('NEGADO', 'Negado')], default='PROCESO', max_length=15)),
                ('concesionaria', models.CharField(choices=[('SURMOTOR', 'Surmotor'), ('GRANDA_CENTENO', 'Granda Centeno'), ('SHYRIS', 'Shyris')], db_index=True, max_length=20)),
                ('vin', models.CharField(db_index=True, max_length=17)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_color', models.CharField(blank=True, max_length=50)),
                ('vehicle_year', models.PositiveSmallIntegerField()),
                ('km_apertura', models.PositiveIntegerField()),
                ('km_cierre', models.PositiveIntegerField()),
                ('codigo_tecnico', models.CharField(max_length=20)),
                ('nro_garantia', models.CharField(blank=True, max_length=20)),
                ('warranty_type_code', models.CharField(blank=True, max_length=10)),
                ('warranty_type_name', models.CharField(blank=True, max_length=200)),
                ('desc_problema', models.TextField(blank=True)),
                ('posibles_causas', models.TextField(blank=True)),
                ('solucion', models.TextField(blank=True)),
                ('cod_naturaleza', models.CharField(blank=True, max_length=100)),
                ('cod_causa', models.CharField(blank=True, max_length=100)),
                ('parte_causal', models.CharField(blank=True, max_length=50)),
                ('campaign_code', models.CharField(blank=True, max_length=20)),
                ('fecha_envio_marca', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='srgs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'srgs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['concesionaria', 'status'], name='srgs_concesi_afab82_idx'), models.Index(fields=['concesionaria', 'srg_type'], name='srgs_concesi_fe4abb_idx')],
            },
        ),
    ]
