# Generated by Django 5.2.14 on 2026-06-02 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_catalog_and_srg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignBody',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('update_name', models.CharField(max_length=200)),
                ('image_link', models.URLField(max_length=500)),
                ('modified_by', models.CharField(blank=True, max_length=150)),
                ('srg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_body', to='persistence.srg')),
            ],
            options={
                'db_table': 'campaign_bodies',
            },
        ),
        migrations.CreateModel(
            name='SrgPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('catalog_code', models.CharField(max_length=20)),
                ('name_es', models.CharField(max_length=200)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('part_origin', models.CharField(max_length=50)),
                ('invoice_number', models.CharField(max_length=50)),
                ('srg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='persistence.srg')),
            ],
            options={
                'db_table': 'srg_parts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(choices=[('BODEGUERO', 'Bodeguero'), ('ASESOR', 'Asesor')], max_length=10)),
                ('action', models.CharField(blank=True, max_length=50)),
                ('modified_by', models.CharField(blank=True, max_length=150)),
                ('srg_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='persistence.srgpart')),
            ],
            options={
                'db_table': 'checklist_items',
                'unique_together': {('srg_part', 'role')},
            },
        ),
    ]
