# Generated by Django 5.2.14 on 2026-06-02 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_srg_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('ot_factura', models.CharField(max_length=20)),
                ('observations', models.TextField()),
                ('concesionaria', models.CharField(choices=[('SURMOTOR', 'Surmotor'), ('GRANDA_CENTENO', 'Granda Centeno'), ('SHYRIS', 'Shyris')], db_index=True, max_length=20)),
                ('additional_emails', models.JSONField(blank=True, default=list)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to=settings.AUTH_USER_MODEL)),
                ('srg', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='audit', to='persistence.srg')),
            ],
            options={
                'db_table': 'audits',
                'ordering': ['-created_at'],
            },
        ),
    ]
