# Generated by Django 5.2.14 on 2026-06-26 21:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0005_srg_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='SrgEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('actor_role', models.CharField(blank=True, choices=[('SUPER_ADMIN', 'Super Admin'), ('JEFE_TALLER', 'Jefe de Taller'), ('ASESOR', 'Asesor'), ('BODEGUERO', 'Bodeguero'), ('AUDITOR', 'Auditor')], max_length=20)),
                ('event_type', models.CharField(choices=[('PART_REQUESTED', 'Repuesto solicitado'), ('RECEPTION_REGISTERED', 'Recepción en bodega'), ('WORK_REGISTERED', 'Repuesto instalado'), ('CORE_RETURN_DECLARED', 'Devolución de core declarada'), ('RETURN_CONFIRMED', 'Devolución confirmada en bodega'), ('STATUS_CHANGED', 'Cambio de estado')], max_length=30)),
                ('quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('state_from', models.CharField(blank=True, max_length=15)),
                ('state_to', models.CharField(blank=True, max_length=15)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='srg_events', to=settings.AUTH_USER_MODEL)),
                ('srg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='persistence.srg')),
                ('srg_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='persistence.srgpart')),
            ],
            options={
                'db_table': 'srg_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ChecklistItem',
        ),
        migrations.AddIndex(
            model_name='srgevent',
            index=models.Index(fields=['srg', 'created_at'], name='srg_events_srg_id_8af590_idx'),
        ),
        migrations.AddIndex(
            model_name='srgevent',
            index=models.Index(fields=['srg_part', 'event_type'], name='srg_events_srg_par_cfcdbd_idx'),
        ),
    ]
